# Generated by Django 2.2 on 2020-09-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitra',
            old_name='nama',
            new_name='nama_mitra',
        ),
    ]
