# Generated by Django 2.2 on 2020-09-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
            ],
        ),
    ]
