# Generated by Django 2.2 on 2020-12-14 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_kegiatan', models.DateField(auto_now=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('judul', models.CharField(max_length=100)),
                ('ket', models.TextField(help_text='maksimal 500 kata', max_length=500)),
                ('selang', models.IntegerField(help_text='Dalam Menit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='catatan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_img', models.FileField(blank=True, default='', upload_to='images/')),
                ('catatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='catatan.Catatan')),
            ],
        ),
    ]
