# Generated by Django 2.2 on 2020-12-14 09:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mitra', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(default='')),
                ('pic', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='forum', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(max_length=200)),
                ('upload_img', models.FileField(blank=True, null=True, upload_to='images/')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posting', to='forum.Forum')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-waktu'],
            },
        ),
        migrations.CreateModel(
            name='Komen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=datetime.datetime.now)),
                ('komentar', models.CharField(max_length=100)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pengguna', to=settings.AUTH_USER_MODEL)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='forum.Posting')),
            ],
        ),
        migrations.CreateModel(
            name='Balas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=datetime.datetime.now)),
                ('balasan', models.TextField()),
                ('komen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='balasan', to='forum.Komen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
