# Generated by Django 2.2 on 2020-12-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dosenpembimbing',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='labsos',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
